---
title: "EnergyMetabolism1"
author: "Robin Myte"
date: "26 september 2016"
output: html_document
---

#DATA IMPORT
```{r import,echo=F}

setwd("/Users/Myte/Dropbox/Documents/JOBB ONKO/Energy-metabolism/results")

# Packages and functions -------------------------
library(cluster)
library(Hmisc)
library(FactoMineR)
library(mgcv)
library(car)
library(boot)
library(gdata)
library(gplots)
library(xlsx)
library(reshape)
library(gdata)                
library(ggExtra)
library(lubridate)
library(dplyr)
library(tidyr)
library(lme4)
library(broom)
library(forcats)
library(circlize)
library(RColorBrewer)
library(survival)

source('~/Dropbox/Documents/JOBB ONKO/R/Kaplan Meier.R')
source("~/Dropbox/Documents/JOBB ONKO/R/confadjust.R")
source('~/Dropbox/Documents/JOBB ONKO/R/table_myte.R')
# Table function, show NA
tab <- function(x,y=1){
  if(length(y)>1){table(x,y,useNA = "always")
    } else{table(x,useNA = "always")} 
} 

# Import data ------------------------- 
# NSHDS kohort data n = 225157, 125381 individer
load("/Users/Myte/Documents/DATA-filer/EnergyMet kohort/crc_enkat.RData")
load("/Users/Myte/Documents/DATA-filer/EnergyMet kohort/crc_enkat old.RData")
options("openxlsx.dateFormat" = "yyyy-mm-dd")
# Import excel (NOT RUN)
#inputcrc <- openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/EnergyMet kohort/Crc_enkat_161124_leveransfil.xlsx",
#                          sheet=1, 
#                           skipEmptyRows=FALSE,
#                           detectDates=T)
# kvalitetsregister-data
kval = openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/EnergyMet kohort/Kvalitetsreg_160921_leverans.xlsx",
                           sheet=1, 
                           skipEmptyRows=FALSE,
                           detectDates=T)
# Create unique ID 
inputcrc <- unite(inputcrc, "id", crc_id,measurement,remove=F)
inputcrc2 <- unite(inputcrc2, "id", crc_id,measurement,remove=F)
inputcrc <- inputcrc[order(inputcrc$id),]
inputcrc2 <- inputcrc2[order(inputcrc2$id),]

# vad är samma? ett häng variabler som är olika!!
identical(inputcrc$id,inputcrc2$id) #ID...duh
inputcrc <- rename(inputcrc, diadat=DIADAT, icdo=ICDO, icd7=ICD7,dodat=DODAT)
var <- names(inputcrc)
same <- matrix(ncol=2,nrow=length(var))
same[,1] <- var
j=0
for(i in var){
  j=j+1
  same[j,2] <-   identical(inputcrc[,i],inputcrc2[,i])
}
same[same[,2]==F,]

identical(inputcrc$q_date,inputcrc2$q_date)
identical(inputcrc$DIADAT,inputcrc2$diadat)
identical(inputcrc$g6,inputcrc2$g6)
#
# MetS variabler ej samma....typ 20 pers mer med NAs
identical(inputcrc$sbt,inputcrc2$sbt)
identical(inputcrc$vikt,inputcrc2$vikt)
identical(inputcrc$dbt,inputcrc2$dbt)
identical(inputcrc$vikt,inputcrc2$vikt)
identical(inputcrc$langd,inputcrc2$langd)
#
apply(inputcrc2,2,function(x) sum(is.na(x)))
apply(inputcrc,2,function(x) sum(is.na(x)))
# Monica dock samma
identical(inputcrc$btsyst,inputcrc2$btsyst)
identical(inputcrc$btdiast,inputcrc2$btdiast)
# id 61931_1
d <- cbind(inputcrc[,c("id","sbt","dbt","vikt")],inputcrc2[,c("id","sbt","dbt","vikt")])
names(d) <- c("id","sbt","dbt","vikt","id2","sbt2","dbt2","vikt2")
identical(d$id,d$id2)

d["diff"] <- d$sbt==d$sbt2
View(d[is.na(d$diff)==T&is.na(d$sbt2)==F,])
d["diff"] <- d$vikt==d$vikt2
View(d[is.na(d$diff)==T&is.na(d$vikt2)==F,])
d <- filter(d, id!= "61931_1")
d["diff"] <- d$vikt==d$vikt2
identical(d$vikt,d$vikt2)
View(d[is.na(d$diff)==T&is.na(d$vikt)==F,])
#
crc <- inputcrc

# Datum och essential variables ----------------
crc["fall"] <- ifelse(crc$crc==1,1,0)
crc$gender <- as.factor(crc$gender)

# Date and time variables
#
# set month = 00 and day = 00 to 06 and 15 
#test <- dplyr::select(crc,q_date,sample_date,dodsdat,DODAT,DIADAT,uppfdat)
# Fix dodsdat
crc$dodsdat <- as.character(crc$dodsdat)
crc[is.na(crc$dodsdat)==F&substr(crc$dodsdat,5,6)=="00","dodsdat"] <- paste0(substr(crc[is.na(crc$dodsdat)==F&substr(crc$dodsdat,5,6)=="00","dodsdat"],1,4),"06",substr(crc[is.na(crc$dodsdat)==F&substr(crc$dodsdat,5,6)=="00","dodsdat"],7,8))
# Set day = 00 to 15
crc[is.na(crc$dodsdat)==F&substr(crc$dodsdat,7,8)=="00","dodsdat"] <- paste0(substr(crc[is.na(crc$dodsdat)==F&substr(crc$dodsdat,7,8)=="00","dodsdat"],1,6),"15")
crc$dodsdat <- ymd(as.numeric(crc$dodsdat))
#Fixa uppfdat
crc$uppfdat <- as.character(crc$uppfdat)
# Set Month = 00 to 06
crc[is.na(crc$uppfdat)==F&substr(crc$uppfdat,5,6)=="00","uppfdat"] <- paste0(substr(crc[is.na(crc$uppfdat)==F&substr(crc$uppfdat,5,6)=="00","uppfdat"],1,4),"06",substr(crc[is.na(crc$uppfdat)==F&substr(crc$uppfdat,5,6)=="00","uppfdat"],7,8))            
# Set day = 00 to 15
crc[is.na(crc$uppfdat)==F&substr(crc$uppfdat,7,8)=="00","uppfdat"] <- paste0(substr(crc[is.na(crc$uppfdat)==F&substr(crc$uppfdat,7,8)=="00","uppfdat"],1,6),"15")
crc$uppfdat <- ymd(as.numeric(crc$uppfdat))
# Fix DIADAT
crc$DIADAT <- ymd(crc$diadat)
#
# Years and attained age
crc["qyear"] <- as.numeric(substr(crc$q_date,1,4))
crc["pyear"] <- as.numeric(substr(crc$sample_date,1,4))
crc["dyear"] <- as.numeric(substr(crc$DIADAT,1,4))
crc["time"] <- (crc$uppfdat-crc$q_date)/365.25 # time difference in years, 365.25 = 1 year
crc["attage"] <- as.numeric(crc$age+crc$time)
crc["diaage"] <- as.numeric(crc$age+(crc$DIADAT-crc$q_date)/365.25)
crc["agef"] <- ceiling(crc$age)
#
#dplyr::select(crc,fall,age,q_date,DIADAT,crc,uppfdat,time,uppfage) %>% View()
#filter(crc,is.na(uppfdat)==T) %>% dplyr::select(fall,age,q_date,DIADAT,crc,uppfdat,time,uppfage) %>% View()

# CRC case verification ----------------
# Kvalitetsregistrert ----------------
kval1 <-  kval %>% 
  mutate_at(c(4:31,33,35:54,56:69,71:92,94:125,126:130,132:134,136:141), funs(as.numeric))
# Fix lokal-variable to make it equivilent to Björn and CRUMS file:
kval1$A2_tumlage_Värde <- na_if(kval1$A2_tumlage_Värde, 9)
kval1$A2_tumlage_Värde <- kval1$A2_tumlage_Värde-1
# rename and create other variables:
kval1 <- dplyr::rename(
                    kval1,crc_id=PERSNR, diaage.k=A0_alder, opererats=A2_oper_Värde, 
                    t=A3_t_Värde, n=A3_n_Värde, m=A3_m_Värde, diffgrad=A3_diffgrad_Värde, 
                    adenocarcinom=A3_adeno_Värde, dvikt=A2_vikt, dlangd=A2_langd, 
                    optyp1=A2_optyp1_Värde,optyp2=A2_optyp2_Värde) %>%
          mutate(
            diadat.k = ymd(A1_Diagnosdatum),
            dyear.k = as.numeric(substr(diadat.k,1,4)),
            opdat = ymd(A2_opdat),
            lokal = ifelse(A2_tumlok_Värde==1,A2_tumlage_Värde,9), 
            lokal3 = cut(lokal,c(-1,0,4,7,11),labels=c("0","1","2","3")))
(a <- apply(kval1,2,function(x) sum(is.na(x)==T)))
a[a==0]
#
# Stadium
# Opererats? 984 ja, 116 nej
# ca 140 saknar TNM värden
dplyr::select(kval1,lokal3,opererats,optyp2,A1_ct1,A1_mr1,t,n,m) %>% apply(2,table,useNA="always")
# en del missing pga år, men även senare år
tab(kval1$t, kval1$dyear.k)
tab(kval1$n, kval1$dyear.k)
tab(kval1$m, kval1$dyear.k)
# I princip samma missing på alla:
tab(kval1$t, kval1$n)
tab(kval1$t, kval1$m)
tab(kval1$n, kval1$m)
# Grade: endast från 2013, olika skalor...bedömningssport 
tab(kval1$diffgrad)
# mer än en cancer? 1066 unika fall, 34 st har mer än 1 post
id <- as.numeric(names(table(kval1$crc_id)[table(kval1$crc_id)>1]))
#filter(kval1,crc_id %in% id) %>% 
#  dplyr::select(crc_id, diadat.k, dyear.k, diaage.k, lokal, lokal3 ,opererats, opdat, t, n, m, diffgrad, dvikt, dlangd) %>%  
#  View()
#filter(kval1,crc_id %in% id) %>% 
#  dplyr::select(crc_id) %>% 
#  table()
length(unique(kval1$crc_id))
# Remove less interesting variables from kval-reg data: 
# "DISTINCT()"removes individauls with more than 1 cancers at same time, should be fixed
kval2 <- dplyr::select(kval1, crc_id, diadat.k, dyear.k, diaage.k, lokal, lokal3 ,opererats, opdat, t, n, m, diffgrad, dvikt, dlangd) %>% 
        distinct(crc_id, .keep_all=T)
summary(kval2)
sum(crc$crc_id %in% kval2$crc_id)
sum(crc$fall==1&(crc$crc_id %in% kval2$crc_id))
# Crate variable in crc-file to indicate which are in kval-reg 
crc["kvalreg"] <- ifelse(crc$crc_id %in% kval2$crc_id,1,0)
tab(crc$kvalreg,crc$measurement)
#
# Folat: ------------
# Björns MSI/BRAF fil - MONICA saknar diagnosdatum
bg2 <- read.csv("~/Documents/DATA-filer/MSI BRAF.csv", sep=";", dec=",",na.strings=c(""," ","NA"))
bg <- openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/EnergyMet kohort/folat_fall.xlsx",
                           sheet=1, 
                           skipEmptyRows=FALSE,
                           detectDates=T)
# "Of the subjects in our present study, 98% had a low ratio of methionine sulfoxide to methionine (less than 10%
# of total plasma concentrations of methionine)""
# set this individual to Filter_folate == 2, not applicable when using folat_fall file
#bg[bg$idnr==4385,"fall"] <- 1
bg <- bg %>% dplyr::select(idnr, pnum,pat_code,Filter_folate, pyear, Age, delproj_num, PAD, dia_age2, 
                                           KRAS, BRAF, MSI, Cimp, diadat2, langd, vikt, Lokal_3:M_TNM, Stadium, 
                                           T_TNM, N_TNM, M_TNM, dodsorsak, Dead, avlidendat, datdiff_km2,-DIADAT) %>% 
                             dplyr::rename(
                                           pyear.bg=pyear, age.bg=Age, diadat.bg=diadat2, lokal.bg=Lokal, lokal3.bg=Lokal_3,
                                           stage.bg=Stadium,langd.bg=langd, vikt.bg=vikt, diaage.bg=dia_age2,
                                           t.bg=T_TNM, n.bg=N_TNM, m.bg=M_TNM,
                                           kras.bg=KRAS, braf.bg=BRAF, msi.bg=MSI, cimp.bg=Cimp) 
bg[bg==9999] <- NA
apply(bg,2,function(x) sum(is.na(x)==T))
#
#vilka crc-fall i bg finns i crc-fil? 636 stycken! 587 unika fall
# 649 när man använder pnum! 
sum(crc$fall==1&(crc$pat_code %in% bg$pat_code))
sum(robin$Pnum %in% bg$pnum)

crc["folatbg"] <- ifelse(crc$fall==1&(crc$pat_code %in% bg$pat_code),1,0)
tab(crc$folatbg,crc$measurement)
#
# CRUMS -------------
# med IDs
# Saved file is Sophias new CRUMS file with attached crc_id from Veronica
load("/Users/Myte/Documents/DATA-filer/EnergyMet kohort/crums161013.Rdata")
# two ids which are in NSHDS have two entries in crums, look up in kvalreg and folate file
dub <- names(table(crums$crc_id)[table(crums$crc_id)>1])
filter(crc, fall==1, crc_id %in% dub)
filter(kval2, crc_id %in% dub)
filter(bg, pat_code == 2480900528)
filter(crums, crc_id %in% dub)
# remove the obs with least concurring data. 
crums <- filter(crums, pad!=199519387,pad!=199900914)
# vilka i NSHDS finns i crums? Några är med men ej prospektiva fall. 141 stycken unika!
sum(crc[,"crc_id"] %in% crums$crc_id)
sum(crc[crc$fall==1,"crc_id"] %in% crums$crc_id)
crc["crums"] <- ifelse(crc$fall==1&(crc$crc_id %in% crums$crc_id),1,0)
tab(crc$crums,crc$measurement)
crums <- dplyr::select(crums, 
                       crc_id, pad, alder, opdatum, dodsdat, fudat, lokal:diffgrad, t.typ, t.front,
                       postkomp.filter, overlevnad.ve.121014, corrstat.ve.121014,
                       kras2grp, braffinal, mmr.2gr.man, k.neg.hi.lonew, cd3.til) %>%
         dplyr::rename(
                       diaage.c=alder,opdatum.c=opdatum,dodsdat.c=dodsdat,
                       lokal.c=lokal, lokal3.c=lokal3, stage.c=stadium, 
                       t.c=tnm.t, n.c=tnm.n, m.c=tnm.m, diffgrad.c=diffgrad, 
                       kras.c=kras2grp, braf.c=braffinal, msi.c=mmr.2gr.man, cimp.c=k.neg.hi.lonew,
                       cd3.til.c=cd3.til)
#
tab(crc$folatbg,crc$kvalreg)
tab(crc$crums,crc$kvalreg)
crc["study"] <- interaction(crc$fall,crc$kvalreg,crc$folatbg,crc$crums)
crc$study <- drop.levels(crc$study)
tab(crc$study)
levels(crc$study) <- c("control","not validated","crums","folat","folat.crums", "kvalreg","kvalreg.crums","kvalreg.folat","kvalreg.folat.crums")
crc$study <- fct_relevel(crc$study,c("kvalreg.folat.crums","kvalreg.folat","kvalreg.crums","folat.crums", 
                                             "kvalreg","folat","crums","not validated","control"))
tab(crc$study,crc$measurement)
crc["validated"] <- crc$study; levels(crc$validated) <- c(rep("validated",7),"not validated","control")
tab(crc$validated,crc$measurement)

# Merge all CRC-case data: 1542 unika fall, 2733 measurements ---------------
# kval reg
crc1 <- filter(crc,fall==1) 
length(unique(crc1$crc_id))
crc1 <- merge(crc1,kval2,id="crc_id",all.x=T)
# Merging worked!
dim(crc1)
tab(crc1$kvalreg,crc1$measurement) 
tapply(crc1$lokal,crc1$kvalreg,summary)
# Folat:
crc1 <- merge(crc1,bg,id="pat_code", all.x=T)
# Merging workded!
dim(crc1)
tab(crc1$folatbg,crc1$measurement) 
tapply(crc1$lokal.bg,crc1$folatbg,summary)
# CRUMS:
crc1 <- merge(crc1,crums,id="crc_id",all.x=T)
# Merging workded!
dim(crc1)
tab(crc1$crums,crc1$measurement) 
tapply(crc1$lokal.c,crc1$crums,summary)

# skapa variabler för när kvalreg/bg/NSHDS diagnosdatum skiljer sig åt:
crc1 <- mutate(crc1, diadat.bg=as.Date(diadat.bg, format="%m/%d/%Y"), 
               kvaldiff=ifelse(is.na(diadat.k)==F&DIADAT!=diadat.k,1,0),
               bgdiff=ifelse(is.na(diadat.bg)==F&DIADAT!=diadat.bg,1,0)
               )

# Vilka är validerade? kvalreg startade 2007
tab(crc1[crc1$measurement==1,"validated"])
tab(crc1[crc1$measurement==1,"validated"], crc1[crc1$measurement==1,"dyear"])
# Hur många måste vi kolla upp?
tab(crc1[crc1$measurement==1,"validated"], crc1[crc1$measurement==1,"kvaldiff"])
# 155 ej validerade + 135 av kvalreg validerade har annat datum än från cancerreg 
#några har dock "rätt" datum i björns fil
#
# Molecular data? 
tab(crc1[crc1$measurement==1,"msi.bg"],crc1[crc1$measurement==1,"delproj"])
tab(crc1[crc1$measurement==1,"kras.bg"],crc1[crc1$measurement==1,"delproj"])
tab(crc1[crc1$measurement==1,"braf.bg"],crc1[crc1$measurement==1,"delproj"])
tab(crc1[crc1$measurement==1,"kras.bg"],crc1[crc1$measurement==1,"kras.c"]) #468 with kras data - 76 MAs
tab(crc1[crc1$measurement==1,"msi.bg"],crc1[crc1$measurement==1,"msi.c"]) #463 with msi data - 74 MAs
#
dplyr::select(crc1, kras.c,braf.c,cimp.c,msi.c,kras.bg,braf.bg,cimp.bg,msi.bg) %>% str()
dplyr::select(crc1, kras.c,braf.c,cimp.c,msi.c,kras.bg,braf.bg,cimp.bg,msi.bg) %>% apply(.,2,tab)
#
# Is CRUMS and BG molecular data the same in cases who are in both projects?
tab(crc1$kras.c,crc1$kras.bg)
tab(crc1$braf.c,crc1$braf.bg)
tab(crc1$msi.c,crc1$msi.bg)
tab(crc1$cimp.c,crc1$cimp.bg)
# change coding in BG KRAS/BRAF variables:
crc1$kras.bg <- ifelse(is.na(crc1$kras.bg)==T,NA,ifelse(crc1$kras.bg==1,0,1))
crc1$braf.bg <- ifelse(is.na(crc1$braf.bg)==T,NA,ifelse(crc1$braf.bg==1,0,1))
# Write file with data för measurement == 1 used to validate data:
crc2 <- crc1 %>% filter(measurement==1) %>% 
         mutate_at(c(200:203, 234:237), funs(as.integer)) %>% #change so that kras/braf,msi,cimp..integers for coalesce
         dplyr::select(crc_id:fasta_prov,dodsdat:bgdiff) %>% 
          mutate(msi.comb = coalesce(msi.bg, msi.c), kras.comb = coalesce(kras.bg, kras.c), 
               braf.comb = coalesce(braf.bg, braf.c),cimp.comb = coalesce(cimp.bg, cimp.c)) %>% 
         dplyr::select(crc_id, Filter_folate, validated, study, kvalreg, folatbg, crums, DIADAT, diadat.k, diadat.bg, 
                      kvaldiff, bgdiff, 
                      diaage, diaage.k, diaage.bg, diaage.c,
                      lokal3, lokal3.bg, lokal3.c, lokal, lokal.bg, lokal.c,  
                      t, n, m, t.bg, n.bg, m.bg, t.c, n.c, m.c , stage.bg, stage.c, 
                      braf.bg, braf.c, braf.comb, kras.bg, kras.c, kras.comb, 
                      msi.bg,msi.c,msi.comb, cimp.bg,cimp.c,cimp.comb, everything()) %>% 
        arrange(desc(validated))
write.xlsx(crc2, file="NSHDS merged crc fall .xlsx")


# Journal-kollad fil: stämmer EJ! 
robin <- openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/EnergyMet kohort/Nshds_merged_crcfall_161101 JOURNALKOLLAD.xlsx",
                          sheet=1, 
                           skipEmptyRows=FALSE,
                           detectDates=T)
#Skapa ad hoc ID med hjälp av diadat och q date:
robin <- unite(robin,"person",DIADAT ,q_date,remove=FALSE)
crc2 <- unite(crc2,"person", DIADAT ,q_date,remove=FALSE)

robin <- robin[order(robin$person),]
crc2 <- crc2[order(crc2$person),]
sum(robin$person==crc2$person)

robin$DIADAT <- ymd(robin$diadat3)
crc2 <- crc2[order(crc2$id),]
robin <- robin[order(robin$id),]
sum(robin$id==crc2$id)






#
# NSHDS Exlcusions  -------------------------
#
# Remove faulty data according to EBF rules, how many with faulty data for some variables: 
# Removed observations: n = 267. n = 258 unika individer tas bort
remove <- filter(crc, langd<130 | langd>210 | vikt<35 | bmi<15 | bmi>70 | midja<60 | skol<0.5 | skol>15 | 
                      skol_mo<0.5 | skol_mo>15 |  hdl<0.15 | hdl>7 | stg<0.15 | stg>20 | stg_mo<0.15 | stg_mo>20 |
                      blods0<1 | blods0>25 | blods2<1 | blods2>35 | sbt<20 | sbt>300 | btsyst<20 | btsyst>300 | 
                      dbt<20 | dbt>250 | btdiast<20 | btdiast>250)
# 224890 obs, 125291 individer
# Ta bort MA: 
# 183444 obs, 119622 individer
crc <- filter(crc,!(id %in% remove$id),delproj!="MA")
ma <- filter(crc,!(id %in% remove$id),delproj=="MA")
#crc <- filter(inputcrc,!(id %in% remove$id))

# Nya Variabler --------------
#crc fall variabel:
crc["fall"] <- ifelse(crc$crc==1,1,0)
# BMI
crc["bmi3"] <- cut(crc$bmi,breaks=c(0,20,25,30,70),right=T,labels=c(1,2,3,4))
#crc$bmi3 <- fct_relevel(crc$bmi3,"2")

# MetS variables
# Normalize variables by analysis methods:
crc["skola"] <- ifelse(crc$efter_090901==1&is.na(crc$efter_090901)==F,0.170+0.939*crc$skol,crc$skol) 
crc["stga"] <- ifelse(crc$efter_090901==1&is.na(crc$efter_090901)==F,0.177+0.932*crc$stg,crc$stg) 
summary(crc$skola-crc$skol)
summary(crc$stga-crc$stg)
# Create combined variables for cohorts:
crc["skolt"] <- ifelse(crc$delproj=="MO",crc$skol_mo,crc$skola)
crc["stgt"] <- ifelse(crc$delproj=="MO",crc$stg_mo,crc$stga)
crc["sbtt"] <- ifelse(crc$delproj=="MO",crc$btsyst,crc$sbt)
crc["dbtt"] <- ifelse(crc$delproj=="MO",crc$btdiast,crc$dbt)
# mid blood pressure
crc["midbp"] <- (crc$sbtt+crc$dbtt)/2
#
#Fasting variable
crc["fasta2"] <- as.factor(crc$fasta_enk);levels(crc$fasta2) <- c(1,2,9999,9999,9999)
crc$fasta2 <- na_if(crc$fasta2,9999)
crc$fasta2 <- drop.levels(crc$fasta2)
crc["fasta22"] <- as.factor(crc$fasta_prov)
levels(crc$fasta22) <- c(2,2,2,1)
crc$fasta22 <- fct_relevel(crc$fasta22,1,2)
crc["fasta"] <- coalesce(crc$fasta2,crc$fasta22)
#levels(crc$fasta) <- c(1,2,9999)
crc[is.na(crc$fasta)==T,"fasta"] <- 2
# check levels within fasting groups, NA and fasta==2 seem similar, set NAs as 2s
tapply(crc$blods0,crc$fasta,summary)
tapply(crc$blods2,crc$fasta,summary)
tapply(crc$skol,crc$fasta,summary)
tapply(crc$stg,crc$fasta,summary)

# Z-transformed variables per gender and sample and fasting
# distributions in groups: 
crc["grouping"] <- drop.levels(interaction(crc$gender, crc$delproj, crc$fasta))
filter(crc, measurement==1) %>% with(.,tab(grouping))
#dplyr::select(crc, grouping, bmi, stgt,dbtt,sbtt,midbp,blods0,skolt) %>% melt(id="grouping") %>%
#  ggplot(aes(x=value, color=grouping)) + geom_density(alpha=0.3) + facet_wrap(~variable,scales="free")
#create variables:
crc<- transform(crc, 
          bmiz=ave(bmi, measurement, delproj, gender, FUN=scale),
          midbpz=ave(midbp, measurement, delproj, gender,  FUN=scale),
          dbtz=ave(dbtt, measurement, delproj, gender,  FUN=scale),
          sbtz=ave(sbtt, measurement, delproj, gender,  FUN=scale),
          stgz=ave(log(stgt), measurement, delproj, gender,fasta,  FUN=scale),
          blods0z=ave(log(blods0), measurement, delproj, gender,fasta,  FUN=scale),
          blods2z=ave(log(blods2), measurement, delproj, gender,fasta,  FUN=scale),
          skolz=ave(skolt, measurement, delproj, gender,fasta,  FUN=scale))
crc["metsz"] <- crc$bmiz + crc$stgz + crc$midbpz + crc$blods0z + crc$skolz

#
# Cut-off MetS
crc["bmi2"] <- ifelse(crc$bmi>=30,1,0)
crc["stg2"] <- ifelse(crc$stgt>=1.7,1,0)
crc["ht2"] <- ifelse(crc$sbtt>=130|crc$dbtt>=85|crc$med_C5a==1,1,0)
crc["gluc2"] <- ifelse(crc$blods0>=5.6,1,0)
crc["skol2"] <- ifelse(crc$skol>=6.2,1,0)
crc["mets"] <- crc$stg2 + crc$ht2 + crc$gluc2 +crc$skol2
crc["mets2"] <- as.factor(ifelse((crc$bmi>=25)&(crc$mets>1),1,0))

# Smoking 
tab(crc$sm_status)
crc["smoke"] <- as.factor(crc$sm_status)
levels(crc$smoke) <- c(5,4,1,3,2,9999,9999)
crc$smoke<- fct_relevel(crc$smoke,"1","2","3","4","5")
tab(crc$smoke)
# Snus
crc["snus"] <- as.factor(crc$sn_status)
levels(crc$snus) <- c(1,2,0,9999,9999)
crc$snus<- fct_relevel(crc$snus,"0")
tab(crc$snus)

# Mediciner variable
dplyr::select(crc,med_C5a:med_C5e,med_C5f,smartmed,med_asahjar, med_asacvs) %>% apply(2,table)
# blodtrycksmedecin
crc[is.na(crc$med_C5a),"med_C5a"] <- 0
crc["htmed"] <- as.factor(crc$med_C5a)
levels(crc$htmed) <- c(0,1,0,0,9999,9999)
# blodfettssänkande
crc[is.na(crc$med_C5e),"med_C5e"] <- 0
crc["bfmed"] <- as.factor(crc$med_C5e)
levels(crc$bfmed) <- c(0,1,0,0,9999,9999)
# Hjärt-kärlkramp 
crc[is.na(crc$med_C5b),"med_C5b"] <- 0
crc["hkmed"] <- as.factor(crc$med_C5b)
levels(crc$hkmed) <- c(0,1,9999,9999)

# Diabetes 
table(crc$diabet)
crc$diabet <- as.factor(crc$diabet)
levels(crc$diabet) <- c(1,0,0,9999,9999,9999)
crc$diabet<- fct_relevel(crc$diabet,"0")
#
# diabetes-behandling:
dplyr::select(crc,diabetesbehandling_a:diabetesbehandling_d) %>% apply(2,tab)
# diet motion
crc[is.na(crc$diabetesbehandling_a),"diabetesbehandling_a"] <- 0
crc$diabetesbehandling_a <- as.factor(crc$diabetesbehandling_a)
levels(crc$diabetesbehandling_a) <- c(0,1,9999,9999)
# tabletter
crc[is.na(crc$diabetesbehandling_b),"diabetesbehandling_b"] <- 0
crc$diabetesbehandling_b <- as.factor(crc$diabetesbehandling_b)
levels(crc$diabetesbehandling_b) <- c(0,1,9999,9999)
# Insulin
crc[is.na(crc$diabetesbehandling_c),"diabetesbehandling_c"] <- 0
crc$diabetesbehandling_c <- as.factor(crc$diabetesbehandling_c)
levels(crc$diabetesbehandling_c) <- c(0,1,9999,9999)
# inget av ovanstående
crc[is.na(crc$diabetesbehandling_d),"diabetesbehandling_d"] <- 0
crc$diabetesbehandling_d <- as.factor(crc$diabetesbehandling_d)
levels(crc$diabetesbehandling_d) <- c(0,1,9999,9999)
dplyr::select(crc,diabetesbehandling_a:diabetesbehandling_d) %>% apply(2,tab)
# Diabetes eller behandling variabel:
crc["diabetes"] <- interaction(
  crc$diabet, crc$diabetesbehandling_a, crc$diabetesbehandling_b,crc$diabetesbehandling_c,crc$diabetesbehandling_d)
crc$diabetes <- drop.levels(crc$diabetes)
levels(crc$diabetes) <- c(0,0,rep(1,8),0,rep(1,9),0,rep(1,3),0,9999)

# 
# Occupationl Physical activity
# VIP:
dplyr::select(crc,g2_a:g2_e) %>% apply(2,tab)
crc <- mutate(crc,g2_a=na_if(g2_a,8888),g2_b=na_if(g2_b,8888),g2_c=na_if(g2_c,8888),g2_d=na_if(g2_d,8888),g2_e=na_if(g2_e,8888))
crc <- mutate(crc,g2_a=na_if(g2_a,9999),g2_b=na_if(g2_b,9999),g2_c=na_if(g2_c,9999),g2_d=na_if(g2_d,9999),g2_e=na_if(g2_e,9999))
#replace NAs with 0
# Slå ihop variabel:
crc["g2"] <- rep(NA,nrow(crc))
crc[is.na(crc$g2_a)==F&crc$g2_a==1,"g2"] <- 1
crc[is.na(crc$g2_b)==F&crc$g2_b==1,"g2"] <- 2
crc[is.na(crc$g2_c)==F&crc$g2_c==1,"g2"] <- 3
crc[is.na(crc$g2_d)==F&crc$g2_d==1,"g2"] <- 4
crc[is.na(crc$g2_e)==F&crc$g2_e==1,"g2"] <- 5
# Set individuals with more than one g2-value to NA: 
crc["g2_sum"] <- crc %>% dplyr::select(g2_a:g2_e) %>% rowSums(.,na.rm=T)
sum(crc$g2_sum>1)
crc[crc$g2_sum>1,"g2"] <- NA
#
# MONICA:
crc <- crc %>% mutate(crc, MONICA_motion_arbete=na_if(MONICA_motion_arbete,8888),MONICA_motion_arbete=na_if(MONICA_motion_arbete,9999))
# COMBINED variable VIP and MONICA:
crc["g2_comb"] <- coalesce(crc$g2, crc$MONICA_motion_arbete)

# Recreationalphysical activity
# VIP
dplyr::select(crc,g6,motion:motion2,MONICA_motion_fritid_86_09) %>% apply(2,tab)
crc <- mutate(crc,g6=na_if(g6,8888),motion=na_if(motion,8888),motion2=na_if(motion2,8888), MONICA_motion_fritid_86_09=na_if(MONICA_motion_fritid_86_09,8888))
crc <- mutate(crc,g6=na_if(g6,6666),motion=na_if(motion,6666),motion2=na_if(motion2,6666), MONICA_motion_fritid_86_09=na_if(MONICA_motion_fritid_86_09,6666))
crc <- mutate(crc,g6=na_if(g6,9999),motion=na_if(motion,9999),motion2=na_if(motion2,9999), MONICA_motion_fritid_86_09=na_if(MONICA_motion_fritid_86_09,9999))
# combine variables for VIP:
crc$motion <- crc$motion+1
crc["g6_vip"] <- coalesce(crc$g6,crc$motion,crc$motion2)
# combine VIP and MONICA:

#
tab(crc$MONICA_motion_fritid_86_09)
crc$g6_MONICA <- as.factor(crc$MONICA_motion_fritid_86_09)
levels(crc$g6_MONICA) <- c(1,2,3,4,5,5,1,2,3,4,5)
crc$g6_MONICA <- as.numeric(crc$g6_MONICA)
# Combined variable MONICA and VIP:
crc["g6_comb"] <- coalesce(crc$g6_vip, crc$g6_MONICA)

# utbild, sätt 5or till 1or
crc$utbild <- as.factor(crc$utbild)
levels(crc$utbild) <- c(1,2,3,4,1,1,9999)

# ursprungsland
crc$ursprungsland <- as.factor(crc$ursprungsland)
levels(crc$ursprungsland) <- c(2,1,9999,9999)
crc$ursprungsland <- relevel(crc$ursprungsland,ref="2")

# maritqal status
crc$civil <- as.factor(crc$civil)
levels(crc$civil) <- c(2,1,3,4,9999,9999,9999,9999)
crc$civil <- relevel(crc$civil,ref="1")

#Birth year:
crc["birthyear"] <- crc$qyear-crc$agef
crc["birthyear5"] <- cut(crc$birthyear,breaks=c(0,1940,1950,1960,1970,2000),labels=c("<1940","1941-50","1951-60","1961-70",">1970"))
#
# Final remove all uncessesary variables:
crc <- dplyr::select(crc, crc_id, crc, fall, measurement:dbt, civil, utbild, ursprungsland, birthyear, birthyear5, uppfdat:diabetes)


# MISSING VIP:
# percent missing in each variable
na.col <- apply(crc,2,function(x) round(sum(is.na(x))/length(x),2))
plot(na.col) #En individ har missing på 60€ av variablerna, (har bara kön och ålder)
na.col[na.col>0.5]

# percent missing in each obs
na.row <- apply(crc,1,function(x) round(sum(is.na(x))/length(x),2))
boxplot(na.row) #En individ har missing på 60€ av variablerna, (har bara kön och ålder)
na.row[na.row>0.5]
crc[names(na.row[na.row>0.5]),] 

#Select and filter crc data
crc <- filter(crc,id!=crc[names(na.row[na.row>0.5]),"id"])


# First measurement data: 
crc1 <- filter(crc,measurement==1)
ma1 <- filter(ma,measurement==1)

# quantile variables
crc1 <- transform(crc1, 
          bmi5=ave(bmi, measurement, delproj, gender, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))),
          midbp5=ave(midbp, measurement, delproj, gender, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))),
          dbt5=ave(dbtt, measurement, delproj, gender, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))),
          sbt5=ave(sbtt, measurement, delproj, gender, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))),
          stg5=ave(stgt, measurement, delproj, gender,fasta, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))),
          blods05=ave(blods0, measurement, delproj, gender,fasta, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))),
          blods25=ave(blods2, measurement, delproj, gender,fasta, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))),
          skol5=ave(skolt, measurement, delproj, gender,fasta, FUN=function(x) cut(x, breaks=quantile(x, probs=seq(0,1,1/5),na.rm=T))))

#correct? YES!
cc <- dplyr::select(crc1, bmi,bmi55,measurement,delproj,gender) %>% sample_n(10)
crc["grouping"] <- drop.levels(interaction(crc$measurement,crc$gender, crc$delproj))
s <- dplyr::select(crc,bmi,measurement,delproj,gender) %>% group_by(measurement,delproj,gender) %>% 
  summarise(m = mean(bmi,na.rm=T), sd = sd(bmi,na.rm=T), 
            q1=quantile(bmi,probs=seq(0,1,1/5),na.rm=T)[1], q2=quantile(bmi,probs=seq(0,1,1/5),na.rm=T)[2],   
            q3=quantile(bmi,probs=seq(0,1,1/5),na.rm=T)[3], q4=quantile(bmi,probs=seq(0,1,1/5),na.rm=T)[4],
            q5=quantile(bmi,probs=seq(0,1,1/5),na.rm=T)[5],q6=quantile(bmi,probs=seq(0,1,1/5),na.rm=T)[6])
s
```

# DESCRIPTIVES
## Histograms anthropometric variables:

```{r historgrams,echo=F}

# Men
filter(crc,measurement==1,gender==1) %>% dplyr::select(fall,age,langd,vikt,bmi,midja,skol_mo,skol,hdl,ldl,stg_mo,stg,blods0,blods2,btsyst,btdiast) %>% mutate(hdl=log(hdl),stg_mo=log(stg_mo),stg=log(stg),blods0=log(blods0),blods2=log(blods2),btsyst=log(btsyst),btdiast=log(btdiast)) %>% melt(id=c("fall")) %>%
  ggplot(aes(x=value, fill=as.factor(fall))) +
  geom_density(alpha=.3)+
  facet_wrap(~variable,scales="free") + theme_bw() 

# Women
filter(crc,measurement==1,gender==2) %>% dplyr::select(fall,age,langd,vikt,bmi,midja,skol_mo,skol,hdl,ldl,stg_mo,stg,blods0,blods2,btsyst,btdiast) %>% mutate(hdl=log(hdl),stg_mo=log(stg_mo),stg=log(stg),blods0=log(blods0),blods2=log(blods2),btsyst=log(btsyst),btdiast=log(btdiast)) %>% melt(id=c("fall")) %>%
  ggplot(aes(x=value, fill=as.factor(fall))) +
  geom_density(alpha=.3)+
  facet_wrap(~variable,scales="free") + theme_bw() 

# BMI per cohort and case-status
filter(crc,measurement==1,gender==2) %>% dplyr::select(bmi,delproj,fall) %>% 
  ggplot(aes(x=bmi, fill=as.factor(fall))) +
  geom_density(alpha=.3)+
  facet_wrap(~delproj) + theme_bw() 

# BMI categories per cohort / sex and case-status 
filter(crc,measurement==1) %>% 
  dplyr::select(bmi3,delproj,fall,gender) %>% 
  mutate(bmi3=relevel(bmi3,ref="1")) %>%
  mutate(bmi3=factor(bmi3,labels=c("<20","20-25","25-30",">30")),gender=factor(gender,labels=c("men","women"))) %>%
  ggplot(aes(x=as.factor(fall), fill=bmi3)) +
  geom_bar(position="fill") + facet_grid(gender~delproj) + xlab("CRC status") + ylab("Proportion")

```

## Basic statistics NSHDS:

```{r antal upprepade enkäter}
#Antal prov per år och cohort
crc %>% dplyr::rename() %>% ggplot(crc,aes(x=as.factor(qyear),fill=delproj)) + 
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 55, hjust = 1)) + 
  facet_wrap(~fall,scales="free") + xlab("")

# antal upprepade mätningar per cohort och fall-status
ggplot(crc,aes(x=as.factor(measurement),fill=delproj)) + geom_bar() + facet_wrap(~fall,scales="free_y") + xlab("Measurement time")

# Sample ålder
ggplot(crc,aes(x=age,fill=delproj)) + geom_histogram() + facet_wrap(~delproj,scales="free_y") + xlab("Age at study entry")

# Diagnos-ålder
ggplot(crc,aes(x=diaage,fill=delproj)) + geom_histogram() + facet_wrap(~delproj,scales="free_y") + xlab("Age at CRC diagnosis")

# hur många har opererats?
crc1 %>% filter(measurement==1) %>% ggplot(aes(x=as.factor(dyear),fill=as.factor(opererats))) + geom_bar(position="fill") + xlab("Year of CRC diagnosis")

```


Growth curves of BMI:

Individual growth curves:
```{r growth curves}
# Sample some cases and non cases:
set.seed(1234)
idcases <- which(crc$fall==1)
idcontrols <- which(crc$crc==5)
id2 <- c(sample(idcases,10),sample(idcontrols,10))

# Growth curves for first 50 individauls 
filter(crc,crc_id %in% id2) %>% ggplot(aes(x=measurement, y=bmi,group=crc_id)) + 
    geom_line(aes(colour=as.factor(fall))) +
    theme_bw()

#
filter(crc,fall==1) %>% ggplot(aes(x=measurement, y=bmi,group=crc_id)) + 
    geom_line(aes(colour=as.factor(gender)), alpha=0.7) +
    #geom_smooth(aes(group=as.factor(crc), color=as.factor(crc)), method="auto") +
    theme_bw()

# FOr CRC case individuals
filter(crc,fall==1) %>% ggplot(aes(x=measurement, y=bmi,group=crc_id)) + 
    geom_line(aes(colour=as.factor(gender)), alpha=0.7) +
    #geom_smooth(aes(group=as.factor(crc), color=as.factor(crc)), method="auto") +
    theme_bw()
```

Venn diagram of crc cases:

```{r,echo=F}
library(VennDiagram)

# A simple three-set diagram
grid.newpage()
venn.plot <- draw.triple.venn(1066, 587, 141,
281, 106, 63, 43, c("CRC quality registry", "Folate project", "CRUMS"))
grid.draw(venn.plot)

```


Cumulative incidence curves:

```{r,echo=F}
library(rms)


crc2 <- filter(crc,measurement==1)
crc2$sex <- factor(crc2$gender, labels=c("men","women"))
crc2 <- transform(crc2, 
          bmi2=ave(bmi, gender, FUN=function(x) cut(x, breaks=quantile(x,probs=c(0,0.80,1),na.rm=T))))
crc2["bmi22"] <- cut(crc2$bmi,breaks=c(0,30,1000),labels=c("BMI < 30","BMI > 30"))
crc2["bmi222"] <- cut(crc2$bmi,breaks=c(0,35,1000),labels=c("<35",">35"))

# Create surv obj
crc2$survobj <- with(crc2, Surv(attage, fall == 1))

## Kaplan-Meier estimator. The "log-log" confidence interval is preferred.
km.as.one <- npsurv(formula = survobj~ 1, data = crc2)
km.by.bmi <- npsurv(formula = survobj~ bmi3, data = crc2)


## Plot cumulative probability F(t) = 1 - S(t)
survplot(km.as.one, fun = function(x) {1 - x}, ylab = "Cumulative Incidence", xlab="Age",
         label.curves = TRUE, xlim=c(50,90),ylim=c(0,0.08))
survplot(km.by.bmi, fun = function(x) {1 - x}, ylab = "Cumulative Incidence", xlab="Age",
         label.curves = TRUE, xlim=c(50,90),ylim=c(0,0.08))
# By sex
par(mfrow=c(1,1))
km.as.sex <- npsurv(formula = survobj~ sex, data = crc2)
survplot(km.as.sex, fun = function(x) {1 - x}, 
         ylab = "Cumulative Incidence", xlab="Age",
         xlim=c(50,85), time.inc = 5 ,ylim=c(0,0.08),grid=TRUE,
          label.curves = list(keys="lines"), col=c("firebrick","blue"), levels.only=TRUE, lty=1,lwd=2)

legend(55, 0.8,c("Males", "Females"), col=c("firebrick","blue"), box.lty=0)

#By Sex and BMI
km.by.bmi1 <- npsurv(formula = survobj~ bmi22, data = crc2[crc2$sex=="men",])
km.by.bmi2 <- npsurv(formula = survobj~ bmi22, data = crc2[crc2$sex=="women",])
par(mfrow=c(1,2))
survplot(km.by.bmi1, fun = function(x) {1 - x}, main="Men",
         ylab = "Cumulative Incidence", xlab="Age",
         xlim=c(50,85), time.inc = 5 ,ylim=c(0,0.08),grid=TRUE,
          label.curves = list(keys="lines"), col=c("firebrick1","firebrick4"),levels.only=TRUE, lty=1,lwd=2)
survplot(km.by.bmi2, fun = function(x) {1 - x}, main="Women",
         ylab = "Cumulative Incidence", xlab="Age",
         xlim=c(50,85), time.inc = 5 ,ylim=c(0,0.08),grid=TRUE,
         label.curves = list(keys="lines"),col=c("firebrick1","firebrick4"),levels.only=TRUE, lty=1,lwd=2)
# Risk ratios:


```

