---
title: "Sophia Early Detection"
author: "Robin Myte"
date: "16 augusti 2016"
output: html_document
---


##Importera data
```{r,echo=FALSE,message=FALSE}

######### Packages RUN ########################### 
library(cluster)
library(Hmisc)
library(FactoMineR)
library(GenABEL)
library(mgcv)
library(car)
library(boot)
library(gdata)
library(gplots)
library(xlsx)
library(reshape)
library(ENmix)
library(gdata)                
library(ggExtra)
library(dplyr)
library(tidyr)
#Functions
source('~/Dropbox/Documents/JOBB ONKO/R/Kaplan Meier.R')
source("~/Dropbox/Documents/JOBB ONKO/R/confadjust.R")
source("~/Dropbox/Documents/JOBB ONKO/R/summ.R")
source("~/Dropbox/Documents/JOBB ONKO/R/RD quartiles.R")
source('~/Dropbox/Documents/JOBB ONKO/R/table_myte.R')
source('~/Dropbox/Documents/JOBB ONKO/R/subtype clog.R')

#Import data
p.inflam = openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/Sophia early detection/NPX and linear_INF.xlsx",
                            rows=1:267,
                           sheet=1, 
                           skipEmptyRows=FALSE)
p.inflamlod = openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/Sophia early detection/NPX and linear_INF.xlsx",
                            rows=1:267,
                           sheet=2, 
                           skipEmptyRows=FALSE)
#p.inflam <- p.inflam[1:266,]
p.onc = openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/Sophia early detection/NPX and linear_ONCII.xlsx",
                           rows=1:270,
                          sheet=1, 
                           skipEmptyRows=FALSE)
p.onclod = openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/Sophia early detection/NPX and linear_ONCII.xlsx",
                           rows=1:270,
                          sheet=2, 
                           skipEmptyRows=FALSE)
#p.onc <- p.onc[1:269,]
phen = openxlsx::read.xlsx(xlsxFile="/Users/Myte/Documents/DATA-filer/Sophia early detection/phenotypdata.xlsx",
                           sheet=1, 
                           skipEmptyRows=FALSE)


#merge
phen["id"] <- phen$pat_code
p.inflam["id"] <- p.inflamlod["id"] <- as.numeric(p.inflam$NPX)
p.onc["id"] <- p.onclod["id"] <- as.numeric(p.onc$NPX)

#NA-data
datx <- merge(p.inflam,p.onc,by="id")
dat1 <- merge(phen,datx,by="id")
dat1 <- unite(dat1,"person",caseset,casecontrol,remove=FALSE)

#LOD-data
datx <- merge(p.inflamlod,p.onclod,by="id")
dat2 <- merge(phen,datx,by="id")
dat2 <- unite(dat2,"person",caseset,casecontrol,remove=FALSE)

#Borttagna flagged prover: (11 stycken), stämmer överrens med OLINKs lista. 
phen[!(phen$id %in% dat1$id),"pat_code"]

#ta bort variabler
dat1 <- select(dat1,-contains("NPX"),-contains("Flagged"))
dat2 <- select(dat2,-contains("NPX"),-contains("Flagged"),-contains("Chip"),-contains("MissData"),-contains("S-Type"))

summary(dat1)

#Data transformation: 182 proteiner

```


RATIO data
```{r,echo=F}


#RATIO DATA:
#Hur många har repeated? 
length(table(dat1$person)[table(dat1$person)==2])
#de som inte har repeated:
ejrep <- names(table(dat1$person)[table(dat1$person)<2])

d1 <- filter(dat1,provnr==1) %>% filter(!(person %in% ejrep))
d2 <- filter(dat1,provnr==2) %>% filter(!(person %in% ejrep))

dat1r <- merge(d1,d2,by="person",all=T)
dat1r <- select(dat1r,-contains("NPX"),-contains("Flagged"),-contains("Chip"),-contains("MissData"),-contains("S-Type"))

#check så det stämmer:
sum(dat1r$gender.x==dat1r$gender.y)
sum(dat1r$caseset.x==dat1r$caseset.y)
sum(dat1r$birth.x==dat1r$birth.y)

#Skapa ratio-variabler:
#summary(dat1r[,c("langd.x","vikt.x","101_IL-8.x","102_VEGF-A.x.x","103_BDNF.x")]/dat1r[,c(c("langd.y","vikt.y","101_IL-8.y","102_VEGF-A.x.y","103_BDNF.y"))])

#dat1r[,13:196] <- dat1r[,208:391]/dat1r[,13:196]
dat1r[,13:196] <- dat1r[,208:391]-dat1r[,13:196]
dat1r <- dat1r[,1:196]

names(dat1r) <- gsub("\\.x", "", names(dat1r))

#RATIO DATA: LOD
#Hur många har repeated? 
length(table(dat2$person)[table(dat2$person)==2])
#de som inte har repeated:
ejrep <- names(table(dat2$person)[table(dat2$person)<2])

d1 <- filter(dat2,provnr==1) %>% filter(!(person %in% ejrep))
d2 <- filter(dat2,provnr==2) %>% filter(!(person %in% ejrep))

dat2r <- merge(d1,d2,by="person",all=T)
dat2r <- select(dat2r,-contains("NPX"),-contains("Flagged"),-contains("Chip"),-contains("MissData"),-contains("S-Type"))

#check så det stämmer:
sum(dat2r$gender.x==dat2r$gender.y)
sum(dat2r$caseset.x==dat2r$caseset.y)
sum(dat2r$birth.x==dat2r$birth.y)

#Skapa ratio-variabler:
#summary(dat2r[,c("langd.x","vikt.x","101_IL-8.x","102_VEGF-A.x.x","103_BDNF.x")]/dat2r[,c(c("langd.y","vikt.y","101_IL-8.y","102_VEGF-A.x.y","103_BDNF.y"))])

#dat2r[,13:199] <- dat2r[,211:397]/dat2r[,13:199]
dat2r[,13:199] <- dat2r[,211:397]-dat2r[,13:199]
dat2r <- dat2r[,1:199]
names(dat2r) <- gsub("\\.x", "", names(dat2r))

```


Samma variabler i onc och infl panel?
```{r,echo=F}
on <- names(p.onc)[2:93]
inf <- names(p.inflam)[2:91]
on <- substr(on,5,nchar(on))
inf <- substr(inf,5,nchar(inf))

inf[inf %in% on]
on[on %in% inf]

summary(select(dat1,contains("VEGF-A")))
summary(select(dat1,contains("HGF")))
```



##Descriptive statistics:


```{r,echo=F}
summary(dat1)
glimpse(dat1)

#corre <- select(dat1,provnr,starts_with("1"))
#datn  <- melt(corre,id="provnr")

#ggplot(datn,aes(x=value,fill=as.factor(provnr)))+geom_histogram()+theme_bw()+facet_wrap(~variable)


```

#heatmap of levels
```{r,echo=F}
corre <- filter(dat1,provnr==1)%>%
          select(starts_with("1"))
dim(corre)

#sort columns
n <- apply(corre,2,function(x) sum(is.na(x)))
n <- sort(n,decreasing=T)
corre <- corre[names(n)]

#sort rows according to ammount of NA
nr <- apply(corre,1,function(x) sum(is.na(x)))
names(nr) <- 1:length(nr)
nr <- sort(nr,decreasing=F)
#corre[is.na(corre)] <- 0
#corre <- apply(corre,2,sort,decreasing=T)

#Heatmap 
# get rownames
corre["names"] <- rownames(corre)
df <- melt(corre,id.vars="names")
df$names <- factor(df$names,levels=names(nr))

g1 <- ggplot(df, aes(names, variable)) + 
   geom_tile(aes(fill = value), colour = "white") + 
   scale_fill_gradient(low = "darkblue",high = "yellow",na.value="white") +
   theme_bw()+labs(x = "", y = "")+
   theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
     legend.position="right")

#Remove legend to add to own square
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}
legend <- get_legend(g1)
g1 <- g1+theme(legend.position="none")

#Margin plots
left <- data.frame(name=1:length(n),value=round(100*n/length(n),0))
top <- data.frame(name=1:length(nr),value=round(100*nr/length(nr),0))

gleft <- ggplot(left, aes(x=name,y=value))+geom_line()+ geom_line(stat="identity")+theme_bw()+labs(x = "", y = "")+
  ylim(c(0,100))+xlim(c(1,182))+
  coord_flip()+ 
  ggtitle("Percent values below detection limit per protein")+ 
    theme(
     axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
     plot.margin = unit(c(0,0,-0.5,0),"cm"),
     panel.margin = unit(c(0,0,-0.5,0),"cm"),
     plot.title = element_text(size=10))

gtop <- ggplot(top, aes(x=name,y=value)) + geom_line()+theme_bw()+labs(x = "", y = "")+
  ylim(c(0,100))+xlim(c(1,133))+
  ggtitle("Percent values below detection limit per indivual")+
  theme(
     axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
     plot.margin = unit(c(0,0,-0.5,0),"cm"),
     panel.margin = unit(c(0,0,-0.5,0),"cm"),
     plot.title = element_text(size=10))
     

#Grid-arrange plot
lay <- rbind(c(NA,1,1,2),
             c(3,4,4,2),
             c(3,4,4,2))
             
grid.arrange(gtop,legend,gleft,g1,layout_matrix=lay,widths=c(0.75,2,2,0.5),heights=c(0.75,2,2)) #7*10 inches




#ggMarginal
g1 <- ggplot(df, aes(names, variable)) + 
   geom_tile(aes(fill = value), colour = "white") + 
   scale_fill_gradient(low = "darkblue",high = "yellow",na.value="white") +
   theme_bw()+labs(x = "", y = "")+
   theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
     legend.position="left")

ggMarginal(g1+
  theme_bw()+
  labs(x = "", y = "")+
  theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.text.y = element_blank(),
  legend.position="left"),
  data=top,x="value",y="name")

```


Cluster analysis heatmap ratios:

```{r,echo=F}

con <- dat2r[,c(8,15:ncol(dat2r))]
con[,-1] <- scale(con[,-1])

heat <- as.matrix(con[,-c(1)])
heat <- t(heat)

#grouping
fcol <- ifelse(con$casecontrol==1,"firebrick","green")

#distance/cluster functions
mydist=function(c) {dist(c,method="euclidian")}
myclust=function(c) {hclust(c,method="complete")}

#heatmap
heatmap.2(heat,
          dendrogram = "both",
          trace="none",
          hclustfun=myclust,
          distfun =mydist,col=bluered(256),
          margins=c(6,12),srtCol=90,ColSideColors=fcol,key.title="Color key",key.xlab="standardized log-concentration")

legend("topright", legend = c("Case", "Control"),fill=c("firebrick","green"),border=FALSE, bty="n", y.intersp = 0.7, cex=0.7)
#legend("topright", legend = c("F840","F845","Control","Missing"),fill=c("green","blue","firebrick","black"),border=FALSE, bty="n", y.intersp = 0.7, cex=0.7)
```





#PCA (NOT SHOWN)

```{r,echo=F}


corre[,-1] <- scale(corre[,-1])
con <- na.omit(corre)
pca <- prcomp(con[,-c(1,2,3,4)],center = FALSE,scale. = FALSE) 
pca;summary(pca)
plot(pca,type="l")

pca1 <- data.frame(prov=con[,1],pca$x[,1:4])

scatterplotMatrix(~PC1+PC2+PC3+PC4|prov, data=pca1,main="PCA",by.groups=F,smoother=F,reg.line=F,col=c("dodgerblue","firebrick"),pch=c(18,20))

```



##Associations biomarkers vs lifestyle


Prov 1: (zntransform on model before does not change sign covariates)

```{r,echo=F}
alpha <- 0.05/182 #alpha level bonferroni corrected

dat21 <- filter(dat1,provnr==1)
dat <- select(dat21,starts_with("1"))

#variables with many NAs
na <- apply(dat,2,function(x) sum(is.na(x))/length(x))
plot(na)
manyna <- names(na[na>=0.8])
#remove them:
dat <- select(dat,-one_of(manyna))

#calculate models
models1 <- lapply(dat, function(q){
   glm(q ~ dat21$casecontrol+dat21$gender+dat21$langd+dat21$vikt)
    })

#get p-values from anova.glm
ps <- lapply(models1,function(x) data.frame(var=names(coef(x)),coef=coef(x),p=anova(x,test="Chisq")$`Pr(>Chi)`))

#extract significant associations
sign <- lapply(ps,function(x) na.omit(x[x$p<=alpha,]))
sign1 <- do.call(rbind, lapply(sign, data.frame, stringsAsFactors=FALSE)) #transform to data frame
sign1

#test
s <- step(models1$"101_IL-8",direction="backward",test="F")


#calculate models with foor loop
var <- names(dat)
mod <- matrix(nrow=ncol(dat),ncol=4)
colnames(mod) <- c("Case","Gender","Length","Weight")
cov <- c("casecontrol","gender","langd","vikt")
rownames(mod) <- var
rdata1 <- dat
j=0
for(i in var){
  j=j+1
  #MODEL
  moddat <- na.omit(dat21[,c(i,cov)])
  g <- glm(moddat[,i]~.,data=moddat[,-1]) #fit model remove NAs
  #ANOVA
  a <-   anova(g,test="Chisq")
  mod[j,] <- a$`Pr(>Chi)`[-1]
  #TRANSFORM data for correlation analysis
  covt <- c(i,"casecontrol",row.names(a)[a$`Pr(>Chi)`<alpha][-1]) #get significant covariates + casecontrol status
  rdata1[,j] <- rntransform(dat21[,i],data=dat21[,covt],family="gaussian") 
}

mod1 <- data.frame(var=rownames(mod),ifelse(mod<=alpha,1,0)) 
sign11 <- mutate(mod1,any.sign=rowSums(mod1[2:5])) %>% filter(any.sign>0) #get significant variables 
sign11
```



Prov 2:

```{r,echo=F}
alpha <- 0.05/182

dat21 <- filter(dat1,provnr==2)
dat <- select(dat21,starts_with("1"))

#variables with many NAs
na <- apply(dat,2,function(x) sum(is.na(x))/length(x))
plot(na)
manyna <- names(na[na>=0.8])
#remove them:
dat <- select(dat,-one_of(manyna))

#calculate models
models1 <- lapply(dat, function(q){
   glm(q ~ dat21$casecontrol+dat21$gender+dat21$langd+dat21$vikt)
    })

#get p-values from anova.glm
ps <- lapply(models1,function(x) data.frame(var=names(coef(x)),coef=coef(x),p=anova(x,test="Chisq")$`Pr(>Chi)`))

#extract significant associations
sign <- lapply(ps,function(x) na.omit(x[x$p<=alpha,]))
sign2 <- do.call(rbind, lapply(sign, data.frame, stringsAsFactors=FALSE)) #transform to data frame
sign2


#calculate models with foor loop
var <- names(dat)
mod <- matrix(nrow=ncol(dat),ncol=4)
colnames(mod) <- c("Case","Gender","Length","Weight")
rownames(mod) <- var
j=0
for(i in var){
  j=j+1
  g <- glm(dat[,i] ~ casecontrol+gender+langd+vikt,data=dat21)
  mod[j,] <- anova(g,test="Chisq")$`Pr(>Chi)`[-1]
}
mod1 <- data.frame(var=rownames(mod),ifelse(mod<=alpha,1,0))
sign22 <- mutate(mod1,any.sign=rowSums(mod1[2:5])) %>% filter(any.sign>0)
sign22
```




Ratio prov 1 och 2:


```{r,echo=F}
alpha <- 0.05/182

dat <- select(dat1r,starts_with("1"))

#variables with many NAs
na <- apply(dat,2,function(x) sum(is.na(x))/length(x))
plot(na)
manyna <- names(na[na>=0.8])
#remove them:
dat <- select(dat,-one_of(manyna))

#calculate models
models1 <- lapply(dat, function(q){
   glm(q ~ dat1r$casecontrol+dat1r$gender+dat1r$langd+dat1r$vikt)
    })

#get p-values from anova.glm
ps <- lapply(models1,function(x) data.frame(var=names(coef(x)),coef=coef(x),p=anova(x,test="Chisq")$`Pr(>Chi)`))

#extract significant associations
sign <- lapply(ps,function(x) na.omit(x[x$p<=alpha,]))
sign3 <- do.call(rbind, lapply(sign, data.frame, stringsAsFactors=FALSE)) #transform to data frame
sign3


#calculate models with foor loop
var <- names(dat)
mod <- matrix(nrow=ncol(dat),ncol=4)
colnames(mod) <- c("Case","Gender","Length","Weight")
rownames(mod) <- var
j=0
for(i in var){
  j=j+1
  g <- glm(dat[,i] ~ casecontrol+gender+langd+vikt,data=dat1r)
  mod[j,] <- anova(g,test="Chisq")$`Pr(>Chi)`[-1]
}
mod1 <- data.frame(var=rownames(mod),ifelse(mod<=alpha,1,0))
sign33 <- mutate(mod1,any.sign=rowSums(mod1[2:5])) %>% filter(any.sign>0)
sign33
```





#Correlations between markers

```{r,echo=F}
#correlations prov 1
cor1 <- cor(rdata1,method="spearman",use="pairwise.complete.obs")
#cor1[is.na(cor1)] <- 0

#correlations prov 2
corre2 <- filter(dat1,provnr==2)%>%
          select(starts_with("1"))
dim(corre2)
cor2 <- cor(corre2,method="spearman",use="pairwise.complete.obs")
#cor2[is.na(cor2)] <- 0

#Correlations ratios:
corre3 <- select(dat1r,starts_with("1"))
dim(corre3)
cor3 <- cor(corre3,method="spearman",use="pairwise.complete.obs")
#cor3[is.na(cor3)] <- 0





#Heatmap 2 : 8*10 inches works good
heat <- t(as.matrix(corre))
dist.pear <- function(x) as.dist(1-cor(t(x),method="spearman",use="pairwise.complete.obs"))
myclust <- function(x) hclust(x, method="average")
#heatmap.2(heat,col=bluered, trace="none", distfun=dist.pear, hclustfun=hclust.ave)
heatmap.2(heat,dendrogram = "row",
          distfun = dist.pear,
          hclustfun = myclust,
          trace="none",
          col=bluered(24),main="",margins=c(10,12),srtCol=55,key.title="Color key",key.xlab="Speaman's correlation")

```








